export const skillsList = [
  { title: 'AMBIDEXTRIE (AD)' },
  { title: 'AGORAPHOBIE (INT)' },
  { title: 'APPEL DES RENFORT' },
  { title: 'APPEL DU SAUVAGE (INT)' },
  { title: 'APPEL DU TONNEAU (INT)' },
  { title: 'APPEL DU VENTRE (INT)' },
  { title: 'ARMES DE BOURRIN' },
  { title: 'ARNAQUE ET CARAMBOUILLE' },
  { title: 'ATTIRE LES MONSTRES' },
  { title: 'BOURRE-PIF' },
  { title: 'BRICOLO DU DIMANCHE (AD)' },
  { title: 'CHANCE DU REMPAILLEUR' },
  { title: 'CHEF DE GROUPE' },
  { title: 'CHERCHER DES NOISES' },
  { title: 'CHEVAUCHER (AD, CHA)' },
  { title: 'CHOURAVER (AD)' },
  { title: 'COMPRENDRE LES ANIMAUX (INT)' },
  { title: 'CUISTOT (AD)' },
  { title: 'DÉPLACEMENT SILENCIEUX (AD)' },
  { title: 'DÉSAMORCER (AD)' },
  { title: 'DÉTECTER (INT)' },
  { title: 'ÉRUDITION (INT)' },
  { title: 'ESCALADER (AD' },
  { title: 'FORGERON (AD)' },
  { title: 'FRAPPER LÂCHEMENT (AT)' },
  { title: 'FARIBOLES (INT, CHA)' },
  { title: 'FOUILLER DANS LES POUBELLES' },
  { title: 'INSTINCT DE SURVIE' },
  { title: 'INSTINCT DU TRESOR (INT)' },
  { title: 'INTIMIDER (COU, CHA)' },
  { title: 'JONGLAGE ET DANSE (AD)' },
  { title: 'LANGUES DES MONSTRES' },
  { title: 'MÉFIANCE (INT)' },
  { title: 'MENDIER ET PLEURNICHER (INT)' },
  { title: 'NAGER (AD, FO)' },
  { title: 'NAÏVETÉ TOUCHANTE (CHA)' },
  { title: 'PÉNIBLE (INT)' },
  { title: 'PISTER (INT)' },
  { title: 'PREMIERS SOINS (AD, INT)' },
  { title: 'RADIN (CHA, INT)' },
  { title: 'RÉCUPÉRATION (PA)' },
  { title: 'RESSEMBLE À RIEN' },
  { title: 'RUNES BIZARRES (INT)' },
  { title: 'SENTIR DES PIEDS' },
  { title: 'SERRURIER (AD)' },
  { title: 'TÊTE VIDE' },
  { title: 'TIRER CORRECTEMENT (AD)' },
  { title: 'TOMBER DANS LES PIÈGE' },
  { title: 'TRUC DE MAUVIETTE (PR)' },
];
